import { Bot, CalendarDays, Check, CreditCard, FileText, Sparkles, Users } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";

import { PageHeader } from "@/components/shared";
import { SubscriptionActions } from "@/components/subscription";
import { Badge, buttonStyles, Card, CardContent, CardHeader, CardTitle, Progress } from "@/components/ui";
import { currentSubscription } from "@/lib/mock-data";
import { formatDate, formatINR } from "@/lib/utils";

export const metadata: Metadata = { title: "Subscription" };

export default function SubscriptionPage() {
  return (
    <div className="app-page-enter space-y-6">
      <PageHeader eyebrow="Plan and usage" title="Subscription" description="Review your plan, usage limits, billing cycle and payment method." actions={[{ label: "Compare plans", href: "/subscription/plans", icon: Sparkles }]} />
      <Card className="overflow-hidden border-primary/25"><div className="grid lg:grid-cols-[1fr_auto]"><div className="p-5 sm:p-6"><div className="flex flex-wrap items-center gap-2"><Badge variant="primary">Pro plan</Badge><Badge variant="success">Active</Badge></div><h2 className="mt-4 text-2xl font-bold">Everything you need to run a growing shop</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Unlimited invoicing, practical AI reports, stronger inventory tools and automatic payment follow-ups.</p><div className="mt-5"><SubscriptionActions /></div></div><div className="border-t border-border bg-primary-soft/45 p-5 lg:min-w-72 lg:border-l lg:border-t-0 sm:p-6"><p className="text-sm text-muted-foreground">Yearly billing</p><p className="mt-1 text-3xl font-bold tracking-[-0.04em]">{formatINR(currentSubscription.price)}</p><p className="mt-4 flex items-center gap-2 text-sm"><CalendarDays className="size-4 text-primary" />Renews {formatDate(currentSubscription.renewalDate)}</p><p className="mt-2 flex items-center gap-2 text-sm"><CreditCard className="size-4 text-primary" />Visa ending 4242</p></div></div></Card>
      <section><div className="mb-4"><h2 className="text-lg font-semibold">Usage this period</h2><p className="mt-1 text-sm text-muted-foreground">Your counters reset on 1 September unless shown otherwise.</p></div><div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="pt-5 sm:pt-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary-soft text-primary"><Bot className="size-5" /></span><div><p className="font-semibold">AI actions</p><p className="text-xs text-muted-foreground">Monthly allowance</p></div></div><Progress value={currentSubscription.aiUsage.used} max={currentSubscription.aiUsage.limit ?? 200} showValue label="Used" valueLabel={`${currentSubscription.aiUsage.used} / ${currentSubscription.aiUsage.limit}`} /></CardContent></Card><Card><CardContent className="pt-5 sm:pt-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-success-soft text-success"><FileText className="size-5" /></span><div><p className="font-semibold">Invoices</p><p className="text-xs text-muted-foreground">Unlimited on Pro</p></div></div><Progress value={38} max={100} showValue label="Created this month" valueLabel="38 / Unlimited" indicatorClassName="bg-success" /></CardContent></Card><Card><CardContent className="pt-5 sm:pt-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-info-soft text-info"><Users className="size-5" /></span><div><p className="font-semibold">Team members</p><p className="text-xs text-muted-foreground">Includes owner</p></div></div><Progress value={currentSubscription.teamMemberUsage.used} max={currentSubscription.teamMemberUsage.limit ?? 3} showValue label="Seats used" valueLabel={`${currentSubscription.teamMemberUsage.used} / ${currentSubscription.teamMemberUsage.limit}`} indicatorClassName="bg-info" /></CardContent></Card></div></section>
      <section className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Included with Pro</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{currentSubscription.features.map((feature) => <div key={feature} className="flex items-center gap-2 text-sm"><span className="grid size-5 place-items-center rounded-full bg-success-soft text-success"><Check className="size-3" /></span>{feature}</div>)}</CardContent></Card><Card><CardHeader><CardTitle>Billing and receipts</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">View subscription invoices, download receipts and check payment status in one place.</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/subscription/billing" className={buttonStyles({ variant: "outline" })}>Billing history</Link><Link href="/subscription/plans" className={buttonStyles()}>Upgrade to Premium</Link></div></CardContent></Card></section>
    </div>
  );
}
