import { Boxes, IndianRupee, Package, Percent, ShoppingBag, TrendingUp, type LucideIcon } from "lucide-react";
import Link from "next/link";

import { ProductActions } from "@/components/products/product-actions";
import { Badge, Card, CardContent, CurrencyDisplay, EmptyState, OrderStatusBadge, StockStatusBadge, Tabs, TabsContent, TabsList, TabsTrigger, buttonStyles } from "@/components/ui";
import { customers } from "@/lib/mock-data";
import { formatDateTime, formatINR } from "@/lib/utils";
import type { InventoryAdjustment, Order, Product } from "@/types";

export function ProductProfile({ product, adjustments, orders }: { product: Product; adjustments: InventoryAdjustment[]; orders: Order[] }) {
  const orderedItems = orders.flatMap((order) => order.items.filter((item) => item.productId === product.id).map((item) => ({ order, item })));
  const unitsSold = orderedItems.reduce((total, entry) => total + entry.item.quantity, 0);
  const sales = orderedItems.reduce((total, entry) => total + entry.item.lineTotal, 0);
  const margin = product.sellingPrice ? Math.round(((product.sellingPrice - product.purchasePrice) / product.sellingPrice) * 100) : 0;
  return <div className="space-y-6">
    <section className="rounded-2xl border border-border bg-card p-5 shadow-card sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 gap-4"><span className="grid size-16 shrink-0 place-items-center rounded-2xl bg-primary-soft text-primary"><Package className="size-8" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight">{product.name}</h1><StockStatusBadge status={product.stockStatus} /></div><p className="mt-1 text-sm text-muted-foreground">{product.sku} · {product.category}</p><div className="mt-3 flex flex-wrap items-center gap-3"><span className="text-xl font-bold"><CurrencyDisplay amount={product.sellingPrice} /></span><Badge variant="outline">{product.currentStock} {product.unit}s in stock</Badge></div></div></div><ProductActions productId={product.id} productName={product.name} /></div></section>
    <Tabs defaultValue="overview"><TabsList className="w-full justify-start"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="movements">Stock movements</TabsTrigger><TabsTrigger value="orders">Recent orders</TabsTrigger></TabsList>
      <TabsContent value="overview" className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Current stock" value={`${product.currentStock} ${product.unit}s`} note={`Alert below ${product.lowStockThreshold}`} icon={Boxes} /><Metric label="Stock value" value={formatINR(product.currentStock * product.purchasePrice)} note="At purchase price" icon={IndianRupee} /><Metric label="Units sold" value={String(unitsSold)} note={`${orders.length} connected orders`} icon={ShoppingBag} /><Metric label="Gross margin" value={`${margin}%`} note={`${formatINR(product.sellingPrice - product.purchasePrice)} per unit`} icon={Percent} /></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(18rem,0.7fr)]"><Card><CardContent className="p-5 sm:p-6"><h2 className="font-semibold">Product information</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{product.description}</p><dl className="mt-5 grid gap-4 sm:grid-cols-2">{[["SKU", product.sku], ["Barcode", product.barcode ?? "Not set"], ["Category", product.category], ["Unit type", product.unit], ["Purchase price", formatINR(product.purchasePrice)], ["Selling price", formatINR(product.sellingPrice)]].map(([label, value]) => <div key={label} className="rounded-xl bg-muted/60 p-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl></CardContent></Card><Card><CardContent className="p-5 sm:p-6"><span className="grid size-10 place-items-center rounded-xl bg-success-soft text-success"><TrendingUp className="size-5" /></span><p className="mt-4 text-xs font-medium text-muted-foreground">Connected sales</p><p className="mt-1 text-2xl font-bold">{formatINR(sales)}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Revenue from orders currently linked to this product.</p></CardContent></Card></div></TabsContent>
      <TabsContent value="movements">{adjustments.length ? <Card className="overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-border bg-muted/60 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Reason</th><th className="px-4 py-3 text-right">Previous</th><th className="px-4 py-3 text-right">Change</th><th className="px-4 py-3 text-right">New</th><th className="px-4 py-3">Changed by</th></tr></thead><tbody>{adjustments.map((item) => <tr key={item.id} className="border-b border-border last:border-0"><td className="px-4 py-4 text-muted-foreground">{formatDateTime(item.date)}</td><td className="px-4 py-4"><Badge variant={item.changedQuantity >= 0 ? "success" : "warning"}>{item.type.replaceAll("_", " ")}</Badge></td><td className="px-4 py-4">{item.reason}</td><td className="px-4 py-4 text-right">{item.previousQuantity}</td><td className={`px-4 py-4 text-right font-semibold ${item.changedQuantity >= 0 ? "text-success" : "text-danger"}`}>{item.changedQuantity > 0 ? "+" : ""}{item.changedQuantity}</td><td className="px-4 py-4 text-right font-semibold">{item.newQuantity}</td><td className="px-4 py-4 text-muted-foreground">{item.changedBy}</td></tr>)}</tbody></table></div><div className="divide-y divide-border md:hidden">{adjustments.map((item) => <article key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.reason}</p><p className="mt-1 text-xs text-muted-foreground">{formatDateTime(item.date)} · {item.changedBy}</p></div><span className={`font-bold ${item.changedQuantity >= 0 ? "text-success" : "text-danger"}`}>{item.changedQuantity > 0 ? "+" : ""}{item.changedQuantity}</span></div><p className="mt-3 text-xs text-muted-foreground">{item.previousQuantity} → {item.newQuantity} units</p></article>)}</div></Card> : <EmptyState title="No stock movements" description="Adjustments and completed sales will appear here." />}</TabsContent>
      <TabsContent value="orders">{orderedItems.length ? <Card className="divide-y divide-border">{orderedItems.map(({ order, item }) => { const customer = customers.find((candidate) => candidate.id === order.customerId); return <article key={`${order.id}-${item.id}`} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><h3 className="font-semibold">{order.orderNumber}</h3><OrderStatusBadge status={order.status} /></div><p className="mt-1 text-xs text-muted-foreground">{customer?.fullName} · {item.quantity} × {formatINR(item.unitPrice)}</p></div><div className="flex items-center justify-between gap-3"><CurrencyDisplay amount={item.lineTotal} className="font-bold" /><Link href={`/orders/${order.id}`} className={buttonStyles({ variant: "outline", size: "sm" })}>View order</Link></div></article>; })}</Card> : <EmptyState title="No connected orders" description="Orders containing this product will be shown here." />}</TabsContent>
    </Tabs>
  </div>;
}

function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: LucideIcon }) { return <Card><CardContent className="p-4 sm:p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-xl font-bold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div><span className="grid size-10 place-items-center rounded-xl bg-primary-soft text-primary"><Icon className="size-5" /></span></div></CardContent></Card>; }
