import type {
  AIConversation,
  AnalyticsSummary,
  Notification,
} from "@/types";

export const analyticsSummary = {
  businessId: "biz_001",
  period: {
    label: "Last 30 days",
    startDate: "2026-07-03T00:00:00.000Z",
    endDate: "2026-08-01T23:59:59.000Z",
  },
  grossSales: 16_883,
  collectedAmount: 8_493,
  outstandingAmount: 8_390,
  averageOrderValue: 3_376.6,
  salesGrowthPercentage: 12.4,
  totalOrders: 5,
  inventoryValue: 36_812,
  lowStockCount: 2,
  outOfStockCount: 1,
  newCustomers: 0,
  returningCustomers: 5,
  revenueTrend: [
    { label: "10 Jul", value: 3_598, previousValue: 2_450 },
    { label: "22 Jul", value: 3_297, previousValue: 2_890 },
    { label: "25 Jul", value: 3_196, previousValue: 3_050 },
    { label: "28 Jul", value: 4_297, previousValue: 3_200 },
    { label: "31 Jul", value: 2_495, previousValue: 3_430 },
  ],
  topProducts: [
    {
      id: "prd_004",
      label: "Redmi 10,000mAh Power Bank",
      value: 3_598,
      secondaryValue: 2,
    },
    {
      id: "prd_003",
      label: "Premium Cotton Shirt",
      value: 3_196,
      secondaryValue: 4,
    },
    {
      id: "prd_001",
      label: "boAt Rockerz 255 Pro+ Earphones",
      value: 2_998,
      secondaryValue: 2,
    },
  ],
  topCustomers: [
    {
      id: "cus_001",
      label: "Rahul Sharma",
      value: 4_297,
      secondaryValue: 2_297,
    },
    {
      id: "cus_003",
      label: "Amit Patel",
      value: 3_598,
      secondaryValue: 3_598,
    },
    {
      id: "cus_005",
      label: "Imran Khan",
      value: 3_297,
      secondaryValue: 0,
    },
  ],
  paymentMethodTotals: {
    cash: 2_000,
    upi: 3_196,
    bank_transfer: 3_297,
  },
  aiInsights: [
    "boAt earphone stock may run out within five days at the current sales rate.",
    "₹3,598 from Amit Patel is overdue; a WhatsApp follow-up is recommended today.",
    "UPI and bank transfers account for 76% of collected payments this period.",
  ],
} satisfies AnalyticsSummary;

export const dashboardMetrics = {
  todaySales: 2_495,
  monthlyRevenue: analyticsSummary.grossSales,
  outstandingPayments: analyticsSummary.outstandingAmount,
  totalCustomers: 6,
  lowStockProducts: analyticsSummary.lowStockCount + analyticsSummary.outOfStockCount,
  pendingOrders: 2,
  paidAmount: analyticsSummary.collectedAmount,
  averageOrderValue: analyticsSummary.averageOrderValue,
  comparisons: {
    todaySales: 8.2,
    monthlyRevenue: analyticsSummary.salesGrowthPercentage,
    outstandingPayments: -4.6,
    totalCustomers: 20,
    lowStockProducts: 1,
    pendingOrders: -1,
  },
} as const;

export const notifications = [
  {
    id: "not_001",
    businessId: "biz_001",
    type: "low_stock_alert",
    category: "inventory",
    title: "boAt earphones are running low",
    description: "Only 8 units remain, below the threshold of 10.",
    href: "/products/prd_001",
    entityId: "prd_001",
    isRead: false,
    readAt: null,
    createdAt: "2026-08-01T03:30:00.000Z",
  },
  {
    id: "not_002",
    businessId: "biz_001",
    type: "payment_received",
    category: "payments",
    title: "₹2,000 payment recorded",
    description: "A cash payment from Rahul Sharma was added to SME-1042.",
    href: "/invoices/inv_001",
    entityId: "pay_001",
    isRead: false,
    readAt: null,
    createdAt: "2026-07-30T10:45:00.000Z",
  },
  {
    id: "not_003",
    businessId: "biz_001",
    type: "payment_overdue",
    category: "payments",
    title: "Invoice SME-1038 is overdue",
    description: "₹3,598 from Amit Patel has been overdue since 17 July.",
    href: "/invoices/inv_003",
    entityId: "inv_003",
    isRead: false,
    readAt: null,
    createdAt: "2026-07-28T08:00:00.000Z",
  },
  {
    id: "not_004",
    businessId: "biz_001",
    type: "invoice_viewed",
    category: "payments",
    title: "Priya Nair viewed SME-1043",
    description: "The invoice was viewed after being sent by email.",
    href: "/invoices/inv_004",
    entityId: "inv_004",
    isRead: true,
    readAt: "2026-07-31T07:12:00.000Z",
    createdAt: "2026-07-31T07:05:00.000Z",
  },
  {
    id: "not_005",
    businessId: "biz_001",
    type: "order_updated",
    category: "orders",
    title: "Order ORD-2043 confirmed",
    description: "Priya Nair's order is ready to prepare for pickup.",
    href: "/orders/ord_005",
    entityId: "ord_005",
    isRead: true,
    readAt: "2026-07-31T06:50:00.000Z",
    createdAt: "2026-07-31T06:40:00.000Z",
  },
  {
    id: "not_006",
    businessId: "biz_001",
    type: "subscription_alert",
    category: "system",
    title: "68 of 200 AI actions used",
    description: "Your Pro plan AI allowance resets on 1 September.",
    href: "/subscription",
    entityId: "sub_001",
    isRead: true,
    readAt: "2026-07-30T04:15:00.000Z",
    createdAt: "2026-07-30T04:00:00.000Z",
  },
  {
    id: "not_007",
    businessId: "biz_001",
    type: "team_activity",
    category: "system",
    title: "Team invitation pending",
    description: "Arjun Meena has not yet accepted the staff invitation.",
    href: "/settings/team",
    entityId: "tm_003",
    isRead: true,
    readAt: "2026-07-30T08:15:00.000Z",
    createdAt: "2026-07-30T08:00:00.000Z",
  },
  {
    id: "not_008",
    businessId: "biz_001",
    type: "ai_recommendation",
    category: "inventory",
    title: "Restock recommendation ready",
    description: "AI-BOS recommends ordering 24 boAt earphones this week.",
    href: "/ai-assistant",
    entityId: "prd_001",
    isRead: false,
    readAt: null,
    createdAt: "2026-08-01T03:45:00.000Z",
  },
] satisfies Notification[];

export const aiConversations = [
  {
    id: "con_001",
    businessId: "biz_001",
    userId: "usr_001",
    title: "Low-stock items",
    messages: [
      {
        id: "msg_001",
        conversationId: "con_001",
        role: "user",
        content: "Show me the items that need restocking.",
        status: "success",
        timestamp: "2026-08-01T03:43:00.000Z",
        feedback: null,
      },
      {
        id: "msg_002",
        conversationId: "con_001",
        role: "assistant",
        content:
          "Three products need attention. The Redmi power bank is out of stock, and the boAt earphones and cotton shirts are below their thresholds.",
        status: "success",
        timestamp: "2026-08-01T03:43:03.000Z",
        resultCard: {
          type: "inventory",
          title: "3 products need attention",
          summary: "Estimated restock value: ₹32,528",
          relatedEntityId: "prd_001",
          fields: [
            { label: "Out of stock", value: 1 },
            { label: "Low stock", value: 2 },
            { label: "Recommended earphone order", value: "24 units" },
          ],
        },
        actions: [
          {
            id: "act_001",
            label: "Review inventory",
            type: "navigate",
            href: "/inventory/low-stock",
          },
          {
            id: "act_002",
            label: "Create restock note",
            type: "confirm",
            requiresConfirmation: true,
          },
        ],
        feedback: null,
      },
    ],
    createdAt: "2026-08-01T03:43:00.000Z",
    updatedAt: "2026-08-01T03:43:03.000Z",
    archivedAt: null,
  },
  {
    id: "con_002",
    businessId: "biz_001",
    userId: "usr_001",
    title: "July sales summary",
    messages: [
      {
        id: "msg_003",
        conversationId: "con_002",
        role: "user",
        content: "Summarise July sales and tell me what to focus on.",
        status: "success",
        timestamp: "2026-07-31T12:40:00.000Z",
        feedback: null,
      },
      {
        id: "msg_004",
        conversationId: "con_002",
        role: "assistant",
        content:
          "You invoiced ₹16,883 across five confirmed orders. ₹8,493 has been collected and ₹8,390 remains outstanding.",
        status: "success",
        timestamp: "2026-07-31T12:40:04.000Z",
        resultCard: {
          type: "analytics",
          title: "July business summary",
          summary: "Sales grew 12.4% compared with the previous period.",
          fields: [
            { label: "Gross sales", value: "₹16,883" },
            { label: "Collected", value: "₹8,493" },
            { label: "Outstanding", value: "₹8,390" },
          ],
        },
        actions: [
          {
            id: "act_003",
            label: "Open analytics",
            type: "navigate",
            href: "/analytics",
          },
          {
            id: "act_004",
            label: "Review outstanding payments",
            type: "navigate",
            href: "/payments/outstanding",
          },
        ],
        feedback: null,
      },
    ],
    createdAt: "2026-07-31T12:40:00.000Z",
    updatedAt: "2026-07-31T12:40:04.000Z",
    archivedAt: null,
  },
] satisfies AIConversation[];

